# Generated by Django 6.0.3 on 2026-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_ign',
            field=models.CharField(default='Leader', help_text='In-game name of the Team Leader / Captain', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players_per_team',
            field=models.PositiveIntegerField(default=4, help_text='Maximum allowed players per team'),
        ),
    ]
