# Generated by Django 6.0.3 on 2026-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_team_leader_ign_tournament_max_players_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_contact',
            field=models.CharField(blank=True, default='', help_text='Phone/WhatsApp number of Team Leader', max_length=15),
        ),
        migrations.AddField(
            model_name='team',
            name='leader_name',
            field=models.CharField(default='', help_text='Actual Full Name of Team Leader / Captain', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_ign',
            field=models.CharField(default='', help_text='In-Game Name (IGN) of Team Leader', max_length=100),
        ),
    ]
