# Generated by Django 6.0.3 on 2026-08-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_team_leader_contact_team_leader_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='total_points',
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_contact',
            field=models.CharField(blank=True, default='', help_text='Phone/WhatsApp number', max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_name',
            field=models.CharField(default='', help_text='Actual Full Name of Team Leader', max_length=100),
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField(default=1, help_text='e.g. 1 for Match 1, 2 for Match 2')),
                ('placement_points', models.PositiveIntegerField(default=0)),
                ('kill_points', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.team')),
            ],
            options={
                'ordering': ['match_number'],
                'unique_together': {('team', 'match_number')},
            },
        ),
    ]
