# Generated by Django 6.0.3 on 2026-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_team_total_points_alter_team_leader_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'match_number'], 'verbose_name': 'Brackets for 1v1 Knockout', 'verbose_name_plural': 'Brackets for 1v1 Knockouts'},
        ),
        migrations.AddField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(choices=[('Left', 'Left Bracket'), ('Right', 'Right Bracket'), ('Final', 'Finals')], default='Left', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False, help_text='True if team automatically passes due to odd team count'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_name',
            field=models.CharField(default='Round 1', max_length=50),
        ),
    ]
