# Generated by Django 6.0.3 on 2026-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_match_options_match_bracket_side_match_is_bye_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round_name',
        ),
        migrations.AlterField(
            model_name='match',
            name='bracket_side',
            field=models.CharField(choices=[('Left', 'Left Side'), ('Right', 'Right Side'), ('Final', 'Finals')], default='Left', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
    ]
