# Generated by Django 6.0.3 on 2026-08-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_match_round_name_alter_match_bracket_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. VR Gaming, WWE 2K24', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='casualgamesession',
            name='game_name',
        ),
        migrations.AddField(
            model_name='casualgamesession',
            name='is_walkin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='casualgamesession',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='events.casualgame'),
        ),
        migrations.CreateModel(
            name='PreRegisteredPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_registered_players', to='events.casualgame')),
            ],
        ),
    ]
