# Generated by Django 6.0.3 on 2026-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_casualgame_remove_casualgamesession_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes or important stuff for this team (e.g. substitutes, payment info, warnings)', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_ign',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
